COMMENT ON TABLE agent_run_event IS 'KodAgent Agent 运行过程事件，保存计划正文、工具调用、子 Agent 摘要和审批事件';
COMMENT ON TABLE agent_run_event_outbox IS 'Agent 事件可靠投递 Outbox，Redis 不可用时用于重试和补偿';
COMMENT ON TABLE agent_approval IS 'Human-in-the-loop 审批事实记录，绑定租户、用户、Run 和草稿';
COMMENT ON TABLE agent_meeting_booking_draft IS '会议室预约 Human-in-the-loop 草稿及审批状态；run/thread/message 是当前轮必填绑定，历史缺失行归档并使用 legacy 标记';
COMMENT ON TABLE assistant IS 'LangGraph Assistant 配置和图入口';
COMMENT ON TABLE assistant_versions IS 'LangGraph Assistant 发布版本';
COMMENT ON TABLE checkpoints IS 'LangGraph 图运行 Checkpoint，保存线程状态快照';
COMMENT ON TABLE checkpoint_blobs IS 'LangGraph Checkpoint 中的序列化状态数据';
COMMENT ON TABLE checkpoint_writes IS 'LangGraph Checkpoint 增量写入记录';
COMMENT ON TABLE checkpoint_delete_queue IS 'LangGraph 待删除 Checkpoint 队列';
COMMENT ON TABLE cron IS 'LangGraph 定时运行任务配置';
COMMENT ON TABLE run IS 'LangGraph Agent Run 执行记录';
COMMENT ON TABLE schema_migrations IS 'LangGraph PostgreSQL Schema 迁移记录';
COMMENT ON TABLE store IS 'LangGraph 持久化键值存储';
COMMENT ON TABLE thread IS 'LangGraph 对话 Thread，保存会话级运行上下文';
COMMENT ON TABLE thread_ttl IS 'LangGraph Thread 生命周期和过期策略';

COMMENT ON COLUMN agent_run_event.id IS '数据库自增主键';
COMMENT ON COLUMN agent_run_event.event_id IS '事件唯一 ID（最长 128 字符），用于幂等去重';
COMMENT ON COLUMN agent_run_event.run_id IS '一次 Agent 运行 ID';
COMMENT ON COLUMN agent_run_event.thread_id IS 'LangGraph 对话 Thread ID';
COMMENT ON COLUMN agent_run_event.message_id IS '用户本轮消息 ID，用于隔离每轮过程';
COMMENT ON COLUMN agent_run_event.tenant_id IS '租户 ID';
COMMENT ON COLUMN agent_run_event.user_id IS '发起用户 ID';
COMMENT ON COLUMN agent_run_event.sequence_no IS 'PostgreSQL 分配的 durable event cursor；不信任客户端 sequence，按此字段重放';
COMMENT ON COLUMN agent_run_event.event_type IS '事件类型，例如 progress、tool.started、approval.required';
COMMENT ON COLUMN agent_run_event.event_data IS '完整事件信封 JSON';
COMMENT ON COLUMN agent_run_event.event_time IS '事件发生时间';
COMMENT ON COLUMN agent_run_event.created_at IS '事件写入数据库时间';
COMMENT ON COLUMN agent_run_event.archived_at IS '事件归档时间，归档不改变审计事实';
COMMENT ON COLUMN agent_run.last_event_cursor IS '最近一次成功落库并应用到运行状态的 durable event cursor，保证状态单调推进';
COMMENT ON COLUMN agent_meeting_booking_draft.draft_id IS '预约草稿 ID';
COMMENT ON COLUMN agent_meeting_booking_draft.owner_user_id IS '草稿所属用户 ID';
COMMENT ON COLUMN agent_meeting_booking_draft.run_id IS '草稿对应的 Agent Run ID；新业务必填，历史缺失行使用 legacy 标记并归档';
COMMENT ON COLUMN agent_meeting_booking_draft.thread_id IS '草稿对应的 LangGraph Thread ID；新业务必填，历史缺失行使用 legacy 标记并归档';
COMMENT ON COLUMN agent_meeting_booking_draft.message_id IS '创建草稿的用户消息 ID；新业务必填，用于隔离当前对话轮次';
COMMENT ON COLUMN agent_meeting_booking_draft.task_id IS '创建草稿的 Agent task/subagent ID';
COMMENT ON COLUMN agent_meeting_booking_draft.status IS '草稿状态：PENDING、SUBMITTED、CANCELLED';
COMMENT ON COLUMN agent_meeting_booking_draft.draft_data IS '预约草稿 JSON 数据';
COMMENT ON COLUMN agent_meeting_booking_draft.result_data IS '预约提交后的业务结果 JSON，用于幂等重试回放';
COMMENT ON COLUMN agent_meeting_booking_draft.expires_at IS '草稿过期时间';
COMMENT ON COLUMN agent_run_event_outbox.event_id IS '对应 agent_run_event.event_id（最长 128 字符）';
COMMENT ON COLUMN agent_run_event_outbox.attempts IS 'Redis 投递尝试次数';
COMMENT ON COLUMN agent_run_event_outbox.next_attempt_at IS '下一次允许重试的时间';
COMMENT ON COLUMN agent_run_event_outbox.published_at IS '成功写入 Redis Stream 的时间';
COMMENT ON COLUMN agent_run_event_outbox.last_error IS '最近一次投递失败原因，禁止写入密钥和身份票据';
COMMENT ON COLUMN agent_approval.tenant_id IS '审批所属租户';
COMMENT ON COLUMN agent_approval.approver_user_id IS '允许操作该审批的用户';
COMMENT ON COLUMN agent_approval.run_id IS '审批对应的 Agent Run ID';
COMMENT ON COLUMN agent_approval.thread_id IS '审批对应的 LangGraph Thread ID';
COMMENT ON COLUMN agent_approval.message_id IS '触发审批的用户消息 ID';
COMMENT ON COLUMN agent_approval.task_id IS '当前 Agent task/subagent ID';
COMMENT ON COLUMN agent_approval.resume_idempotency_key IS 'LangGraph resume 请求幂等键';
COMMENT ON COLUMN agent_approval.resumed_at IS '恢复请求记录时间';
COMMENT ON COLUMN agent_approval.idempotency_key IS '确认或拒绝操作幂等键';
COMMENT ON COLUMN agent_approval.status IS 'PENDING、APPROVED、REJECTED、EXPIRED';
COMMENT ON COLUMN agent_approval.draft_type IS '审批卡片草稿类型';
COMMENT ON COLUMN agent_approval.draft_data IS '通用审批卡片快照';
COMMENT ON COLUMN agent_meeting_booking_draft.tenant_id IS '草稿所属租户';
COMMENT ON COLUMN agent_meeting_booking_draft.idempotency_key IS '同一租户、用户、Run、Thread、Message 请求的草稿幂等键';
COMMENT ON COLUMN agent_meeting_booking_draft.archived_at IS '草稿归档时间，业务删除使用状态变更';
